-- DEFINE FUNCTION generate_uuid13() RETURN AN UUID WITH 13 CHARACTERS
CREATE FUNCTION generate_uuid13() RETURNS varchar(13) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    NO SQL
BEGIN
    DECLARE i INT DEFAULT 13;
    DECLARE uuid VARCHAR(13) DEFAULT '';
    REPEAT
        SET uuid = CONCAT(uuid,SUBSTR('0123456789ABCDEFGHJKMNPQRSTVWXYZ', FLOOR(1 +(RAND() * 32)), 1));
        SET i = i - 1;
    UNTIL i = 0 END REPEAT;
    RETURN uuid;
END;

-- DEFINE FUNCTION generate_uuid26() RETURN AN UUID WITH 26 CHARACTERS
CREATE FUNCTION generate_uuid26() RETURNS varchar(26) CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci
    NO SQL
BEGIN
    DECLARE i INT DEFAULT 26;
    DECLARE uuid VARCHAR(26) DEFAULT '';
    REPEAT
        SET uuid = CONCAT(uuid,SUBSTR('0123456789ABCDEFGHJKMNPQRSTVWXYZ', FLOOR(1 +(RAND() * 32)), 1));
        SET i = i - 1;
    UNTIL i = 0 END REPEAT;
    RETURN uuid;
END;
