-- DEFINE FUNCTION generate_uuid13() RETURN AN UUID WITH 13 CHARACTERS
CREATE FUNCTION generate_uuid13() RETURNS varchar(13) CHARSET utf8mb4 COLLATE utf8_unicode_ci
    NO SQL
BEGIN
    DECLARE i INT DEFAULT 13;
    DECLARE uuid VARCHAR(13) DEFAULT '';
    REPEAT
        SET uuid = CONCAT(uuid,SUBSTR('0123456789ABCDEFGHJKMNPQRSTVWXYZ', FLOOR(1 +(RAND() * 32)), 1));
        SET i = i - 1;
    UNTIL i = 0 END REPEAT;
    RETURN uuid;
END

-- DEFINE FUNCTION generate_uuid26() RETURN AN UUID WITH 26 CHARACTERS
CREATE FUNCTION generate_uuid26() RETURNS varchar(26) CHARSET utf8mb4 COLLATE utf8_unicode_ci
    NO SQL
BEGIN
    DECLARE i INT DEFAULT 26;
    DECLARE uuid VARCHAR(26) DEFAULT '';
    REPEAT
        SET uuid = CONCAT(uuid,SUBSTR('0123456789ABCDEFGHJKMNPQRSTVWXYZ', FLOOR(1 +(RAND() * 32)), 1));
        SET i = i - 1;
    UNTIL i = 0 END REPEAT;
    RETURN uuid;
END

-- DEFINE THE PERMISSIONS TABLE
CREATE TABLE TB_PERMISSIONS (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL UNIQUE,
    NAME VARCHAR(127) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE ROLES TABLE
CREATE TABLE TB_ROLES (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL UNIQUE,
    NAME VARCHAR(127) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE TB_ROLE_PERMISSION TABLE
CREATE TABLE TB_ROLE_PERMISSION (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID BIGINT UNSIGNED NOT NULL,
    PERMISSION_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `ROLE_PERMISSION_ROLE_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_ROLES` (`ID`) ON DELETE CASCADE,
    CONSTRAINT `ROLE_PERMISSION_PERMISSION_FK` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `TB_PERMISSIONS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE TB_USERS TABLE
CREATE TABLE TB_USERS (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL UNIQUE,
    NAME VARCHAR(127) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE_ID BIGINT UNSIGNED NOT NULL,
    ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `USERS_ROLE_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_ROLES` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE TB_ACCOUNT TABLE
CREATE TABLE TB_ACCOUNT (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL UNIQUE, 
    NAME VARCHAR(127) NOT NULL,
    ADDRESS_1 VARCHAR(127) NOT NULL, 
    ADDRESS_2 VARCHAR(127), 
    ADDRESS_3 VARCHAR(127),
    COUNTY VARCHAR(127) NOT NULL, 
    CITY VARCHAR(127) NOT NULL, 
    ZIP_CODE VARCHAR(15) NOT NULL, 
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(20), 
    MOBILE_NUMBER VARCHAR(20), 
    CONTACT VARCHAR(127), 
    VERIFIED BOOLEAN DEFAULT FALSE, 
    BLOCKED BOOLEAN DEFAULT FALSE, 
    ACTIVED BOOLEAN DEFAULT FALSE, 
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE TB_ACCOUNT_VERIFY TABLE
CREATE TABLE TB_ACCOUNT_VERIFY (
    ACCOUNT_ID BIGINT UNSIGNED NOT NULL PRIMARY KEY, 
    TOKEN_GENERATED CHAR(13) NOT NULL, 
    TOKEN_EXPIRED_AT TIMESTAMP NOT NULL, 
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
