-- DEFINE THE PERMISSIONS TABLE FOR SAAS_ERP_ADMIN
CREATE TABLE TB_PERMISSIONS (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL,
    NAME VARCHAR(127) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE ROLES TABLE FOR SAAS_ERP_ADMIN
CREATE TABLE TB_ROLES (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    UUID CHAR(13) NOT NULL,
    NAME VARCHAR(127) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- DEFINE THE TB_ROLE_PERMISSION TABLE FOR SAAS_ERP_ADMIN
CREATE TABLE TB_ROLE_PERMISSION (
    ID BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ROLE_ID BIGINT UNSIGNED NOT NULL,
    PERMISSION_ID BIGINT UNSIGNED NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `ROLE_PERMISSION_ROLE_FK` FOREIGN KEY (`ROLE_ID`) REFERENCES `TB_ROLES` (`ID`) ON DELETE CASCADE,
    CONSTRAINT `ROLE_PERMISSION_PERMISSION_FK` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `TB_PERMISSIONS` (`ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

